substitutions:
  _ENV: "Dev"
  _PLAN_BUCKET_NAME: ""  # Replace with your bucket name

steps:
- id: 'validate'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      echo "branch $BRANCH_NAME"
      echo "run init"
      cd ${_ENV}
      terraform init
      echo "run validate"
      terraform validate
      echo "check backend connection"
      terraform providers


- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      echo "run plan and save to GCS bucket"
      cd ${_ENV}
      terraform plan -out terraform.plan


# Step to copy the plan file to a GCS bucket using gsutil
- id: 'upload plan to GCS'
  name: 'gcr.io/cloud-builders/gsutil'
  args:
  - 'cp'
  - '${_ENV}/terraform.plan'
  - 'gs://my-test-bucketdevops9700/$BRANCH_NAME/${_ENV}/$COMMIT_SHA/terraform.plan'

- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      echo "apply the plan from GCS bucket"
      cd ${_ENV}
      terraform apply -auto-approve terraform.plan
options:
  logging: CLOUD_LOGGING_ONLY
