steps:
  - name: gcr.io/cloud-builders/gsutil
    args:
      - cp
      - >-
        gs://my-test-bucketdevops9700/${_BRANCH_NAME}/${_ENV}/${_COMMIT_SHA}/terraform-artifacts.zip
      - ./terraform-artifacts.zip
    id: download-plan
  - name: gcr.io/cloud-builders/gsutil
    args:
      - '-c'
      - |
        echo "Unzipping the plan file..."
        unzip terraform-artifacts.zip
    id: unzip-plan
    entrypoint: sh
  - name: 'hashicorp/terraform:1.0.0'
    args:
      - '-c'
      - |
        echo "Applying the Terraform plan..."
        cd ${_ENV}
        terraform init -input=false
        terraform apply -auto-approve terraform.plan
    id: terraform-apply
    entrypoint: sh
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _COMMIT_SHA: ''
  _BRANCH_NAME: ''
  _ENV: ''
